### ISSUE TITLE
Hard dep on json2csv 3.7 does not resolve

### ISSUE THREAD

**Issue by cvkline** [emeeks/semiotic#192]
Doing a clean `npm install` on a new project results in a node_modules tree containing an error that json2csv@3.7.4 is unresolved. I can successfully pull in the latest ^3 version of that module which is 3.11.5 but for some reason 3.7.4 can't be pulled. I don't know if that's a transient problem or what, but I thought I would mention it.

There don't appear to be any breaking changes until version 4, so this might be fairly easy to fix... I might give it a try;  I thought I'd let you know about it in any case.

**Comment by emeeks** [comment]
You know I've heard json2csv giving people problems installing for a while but I never thought it was based on the version. This would be great to resolve, I was planning to just tear out the download feature entirely.

**Comment by cvkline** [comment]
I wonder if the resolution isn't as simple as upping the version to 3.11.5 and re-running tests?

There's probably also a way to create CSVs entirely in the d3 world. I may clone and fiddle.

**Comment by emeeks** [comment]
I'm looking into this with the hope of publishing a fix, did you see any other possible concerns?

**Comment by cvkline** [comment]
There appear to be no breaking changes with the latest version so presumably the answer to your question is no.

I just merged semiotic into our product's package.json and the busted 3.7.3 dep is apparently causing heartache with the automated build process, so this is becoming somewhat of an elevated priority for us.

**Comment by cvkline** [comment]
That's very odd, because the only change in package.json between 1.9.1 and 1.9.2 was the version bump to semiotic itself. This is very confusing.

**Comment by ZachHaber** [comment]
Yeah, it really is odd, I even tried directly copying the node_modules/semiotic folder from the old repository (where it was working) to the new one I had just clean installed, and the error remained. It wasn't until I switched semiotic versions that the error resolved itself.

**Comment by cvkline** [comment]
I just made pull request #196 which is pretty trivial but does seem to fix the version error.

**Comment by emeeks** [comment]
Updated in 1.9.3
